config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get '/residential', to: 'home#residential'
  get '/commercial', to: 'home#commercial'
  get '/quote', to: 'home#quote'
  get '/index', to: 'home#index'
  get '/intervention', to: 'home#intervention' 
  post '/create_quotes' =>'quotes#create'
  post '/create_leads' => 'leads#create'
  get '/users/:id' , to: 'users#show'
  get '/users/:id/edit', to: 'users#edit', :as => :user
  patch '/users/:id/edit' => 'users#update'
  get '/update_building/:customer_id', to: 'interventions#updateBuildings'
  get '/update_battery/:building_id', to: 'interventions#updateBattery'
  get '/update_column/:battery_id', to: 'interventions#updateColumn'
  get '/update_elevator/:column_id', to: 'interventions#updateElevator'
  post '/intervention/create_intervention', to: 'interventions#submit'
  resource :intervention

  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'
  # get '/audio', to: 'admin/dashboard#file'

  get 'admin/ibm_call' => 'admin/dashboard#ibm_call'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :customers, dependent: :destroy
    has_many :buildings, dependent: :destroy

  def to_s 
    "Address #" + self.id.to_s
  end
end

app/models/battery.rb
class Battery < ApplicationRecord
  belongs_to :building
  belongs_to :employee
  has_many :columns, dependent: :destroy
  has_many :intervention


  def to_s
    "Battery #" + self.id.to_s
  end
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :customer
  belongs_to :address
  has_one :building_detail, dependent: :destroy
  has_many :batteries, dependent: :destroy
  has_many :intervention
  
  def to_s 
    "Building #" + self.id.to_s
  end

end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
  belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :battery
  has_many :elevators, dependent: :destroy
  has_many :intervention

  def to_s 
    "Column #" + self.id.to_s
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # attr_reader :user_id, :customer_creation_date, :company_name, :company_headquarters_address, :full_name_of_the_company_contact,
  #   :company_contact_phone, :email_of_the_company_contact, :company_description, :technical_authority_phone_for_service, :technical_manager_email_for_service

  belongs_to :user
  belongs_to :address
  has_many :buildings, dependent: :destroy
  has_many :intervention

  def to_s 
    "Customer #" + self.id.to_s
  end
end

app/models/dim_customer.rb
class DimCustomer < ApplicationRecord

end

app/models/elevator.rb
class Elevator < ApplicationRecord
  belongs_to :column
  has_many :intervention

  def to_s
    "Elevator #" + self.id.to_s
  end
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
    belongs_to :user 
    has_many :batteries, dependent: :destroy
    has_many :intervention

        def to_s
        "Employee #" + self.id.to_s
    end
end

app/models/fact_contact.rb
class FactContact < ActiveRecord::Base
    establish_connection(:data_warehouse)
end

app/models/fact_elevator.rb
class FactElevator < ActiveRecord::Base
end

app/models/fact_quote.rb
class FactQuote < ActiveRecord::Base
#      ActiveRecord::Base.establish_connection(:data_warehouse)
    establish_connection(:data_warehouse)
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :employee
    belongs_to :customer
    belongs_to :building
    belongs_to :battery
    belongs_to :column 
    belongs_to :elevator
  
    def to_s
      "Intervention #" + self.id.to_s
    end
    def new
      @intervention = intervention.new
    end 
  end

app/models/lead.rb
class Lead < ApplicationRecord
    has_one_attached :contact_attachment_file
    # after_create :send_email
    # after_create :upload_dropbox
    
    def attachment_path

    end

    def to_s
        "Lead #" + self.id.to_s
    end
    
    private

    def send_email
        Sendgrid.new(self).call
    end

    def upload_dropbox
        Dropbox.new(self).call
    end
end

app/models/quote.rb
# frozen_string_literal: true

class Quote < ApplicationRecord
end

app/models/sendgrid_mailer.rb
class SendgridMailer
  def self.send(to, subsitutions, template_id)
    data = {
      "personalizations": [
        {
          "to": [
            {
              "email": to
            }
          ],
          "dynamic_template_data": subsitutions
        }
      ],
      "from": {
        "email": 'noreply@example.com'
      },
      "template_id": template_id
    }
    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    begin
      response = sg.client.mail._("send").post(request_body: data)
      return response.status_code
    rescue Exception => e
      puts e.message
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :employees, dependent: :destroy
  has_one :customer, dependent: :destroy
  # class_name: "employee", foreign_key: "employees_id" i did remove this one it works with it though

  def to_s
    self.first_name + " " + self.last_name
  end
end

app/controllers/quotes_controller.rb
# frozen_string_literal: true

class QuotesController < ApplicationController
  before_action :set_quote, only: %i[show edit update destroy]
  protect_from_forgery except: :home
  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show; end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit; end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to root_path, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end

    ZendeskAPI::Ticket.create!(@client,
    :subject => "#{@quote.company_name}",
    :comment => { :value =>
      "The company #{@quote.company_name} has made a quote for a building of type #{@quote.building_type} and wants the #{@quote.product_line} service.
      Quote Information:
      amount of elevators: #{@quote.amount_elevators}
      installation fees: #{@quote.installation_fees}
      total: #{@quote.total_cost}" },
    :type => "task",
    :priority => "urgent")

  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to root_path, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quote
    @quote = Quote.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def quote_params
    params.permit(:building_type, :amount_elevators, :product_line, :installation_fees, :total_cost,
                  :amount_floors, :amount_basements, :amount_parking_spots, :maximum_occupancy, :amount_apartments,
                  :amount_companies, :amount_corporations, :business_hours, :email, :company_name)
  end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
# frozen_string_literal: true

module QuotesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :building_type %>
    <%= form.text_field :building_type %>
  </div>

  <div class="field">
    <%= form.label :amount_elevators %>
    <%= form.text_field :amount_elevators %>
  </div>

  <div class="field">
    <%= form.label :product_line %>
    <%= form.text_field :product_line %>
  </div>

  <div class="field">
    <%= form.label :installation_fees %>
    <%= form.text_field :installation_fees %>
  </div>

  <div class="field">
    <%= form.label :total_cost %>
    <%= form.text_field :total_cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Building type</th>
      <th>Amount elevators</th>
      <th>Product line</th>
      <th>Installation fees</th>
      <th>Total cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.building_type %></td>
        <td><%= quote.amount_elevators %></td>
        <td><%= quote.product_line %></td>
        <td><%= quote.installation_fees %></td>
        <td><%= quote.total_cost %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building type:</strong>
  <%= @quote.building_type %>
</p>

<p>
  <strong>Amount elevators:</strong>
  <%= @quote.amount_elevators %>
</p>

<p>
  <strong>Product line:</strong>
  <%= @quote.product_line %>
</p>

<p>
  <strong>Installation fees:</strong>
  <%= @quote.installation_fees %>
</p>
<p>
  <strong>Email:</strong>
  <%= @quote.email %>
</p>
<p>
  <strong>Company Name:</strong>
  <%= @quote.company_name %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @quote.total_cost %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |