config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get '/residential', to: 'home#residential'
  get '/commercial', to: 'home#commercial'
  get '/quote', to: 'home#quote'
  get '/index', to: 'home#index'
  get '/intervention', to: 'home#intervention' 
  post '/create_quotes' =>'quotes#create'
  post '/create_leads' => 'leads#create'
  get '/users/:id' , to: 'users#show'
  get '/users/:id/edit', to: 'users#edit', :as => :user
  patch '/users/:id/edit' => 'users#update'
  get '/update_building/:customer_id', to: 'interventions#updateBuildings'
  get '/update_battery/:building_id', to: 'interventions#updateBattery'
  get '/update_column/:battery_id', to: 'interventions#updateColumn'
  get '/update_elevator/:column_id', to: 'interventions#updateElevator'
  post '/intervention/create_intervention', to: 'interventions#submit'
  resource :intervention

  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'
  # get '/audio', to: 'admin/dashboard#file'

  get 'admin/ibm_call' => 'admin/dashboard#ibm_call'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :customers, dependent: :destroy
    has_many :buildings, dependent: :destroy

  def to_s 
    "Address #" + self.id.to_s
  end
end

app/models/battery.rb
class Battery < ApplicationRecord
  belongs_to :building
  belongs_to :employee
  has_many :columns, dependent: :destroy
  has_many :intervention


  def to_s
    "Battery #" + self.id.to_s
  end
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :customer
  belongs_to :address
  has_one :building_detail, dependent: :destroy
  has_many :batteries, dependent: :destroy
  has_many :intervention
  
  def to_s 
    "Building #" + self.id.to_s
  end

end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
  belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :battery
  has_many :elevators, dependent: :destroy
  has_many :intervention

  def to_s 
    "Column #" + self.id.to_s
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # attr_reader :user_id, :customer_creation_date, :company_name, :company_headquarters_address, :full_name_of_the_company_contact,
  #   :company_contact_phone, :email_of_the_company_contact, :company_description, :technical_authority_phone_for_service, :technical_manager_email_for_service

  belongs_to :user
  belongs_to :address
  has_many :buildings, dependent: :destroy
  has_many :intervention

  def to_s 
    "Customer #" + self.id.to_s
  end
end

app/models/dim_customer.rb
class DimCustomer < ApplicationRecord

end

app/models/elevator.rb
class Elevator < ApplicationRecord
  belongs_to :column
  has_many :intervention

  def to_s
    "Elevator #" + self.id.to_s
  end
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
    belongs_to :user 
    has_many :batteries, dependent: :destroy
    has_many :intervention

        def to_s
        "Employee #" + self.id.to_s
    end
end

app/models/fact_contact.rb
class FactContact < ActiveRecord::Base
    establish_connection(:data_warehouse)
end

app/models/fact_elevator.rb
class FactElevator < ActiveRecord::Base
end

app/models/fact_quote.rb
class FactQuote < ActiveRecord::Base
#      ActiveRecord::Base.establish_connection(:data_warehouse)
    establish_connection(:data_warehouse)
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :employee
    belongs_to :customer
    belongs_to :building
    belongs_to :battery
    belongs_to :column 
    belongs_to :elevator
  
    def to_s
      "Intervention #" + self.id.to_s
    end
    def new
      @intervention = intervention.new
    end 
  end

app/models/lead.rb
class Lead < ApplicationRecord
    has_one_attached :contact_attachment_file
    # after_create :send_email
    # after_create :upload_dropbox
    
    def attachment_path

    end

    def to_s
        "Lead #" + self.id.to_s
    end
    
    private

    def send_email
        Sendgrid.new(self).call
    end

    def upload_dropbox
        Dropbox.new(self).call
    end
end

app/models/quote.rb
# frozen_string_literal: true

class Quote < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :employees, dependent: :destroy
  has_one :customer, dependent: :destroy
  # class_name: "employee", foreign_key: "employees_id" i did remove this one it works with it though

  def to_s
    self.first_name + " " + self.last_name
  end
end

app/controllers/elevators_controller.rb
class ElevatorsController < InheritedResources::Base

  private

    def elevator_params
      params.require(:elevator).permit(:column_id, :serial_number, :model, :type, :status, :Date_of_commissioning, :date_of_last_inspection, :certificate_of_inspection, :information, :notes)
    end

end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
# frozen_string_literal: true

module QuotesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/elevators/_form.html.erb
<%= form_with(model: elevator, local: true) do |form| %>
  <% if elevator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elevator.errors.count, "error") %> prohibited this elevator from being saved:</h2>

      <ul>
      <% elevator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :column_id %>
    <%= form.text_field :column_id %>
  </div>

  <div class="field">
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :Date_of_commissioning %>
    <%= form.date_select :Date_of_commissioning %>
  </div>

  <div class="field">
    <%= form.label :date_of_last_inspection %>
    <%= form.date_select :date_of_last_inspection %>
  </div>

  <div class="field">
    <%= form.label :certificate_of_inspection %>
    <%= form.text_field :certificate_of_inspection %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_area :information %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elevators/edit.html.erb
<h1>Editing Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Show', @elevator %> |
<%= link_to 'Back', elevators_path %>

app/views/elevators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elevators</h1>

<table>
  <thead>
    <tr>
      <th>Column</th>
      <th>Serial number</th>
      <th>Model</th>
      <th>Type</th>
      <th>Status</th>
      <th>Date of commissioning</th>
      <th>Date of last inspection</th>
      <th>Certificate of inspection</th>
      <th>Information</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevators.each do |elevator| %>
      <tr>
        <td><%= elevator.column %></td>
        <td><%= elevator.serial_number %></td>
        <td><%= elevator.model %></td>
        <td><%= elevator.type %></td>
        <td><%= elevator.status %></td>
        <td><%= elevator.Date_of_commissioning %></td>
        <td><%= elevator.date_of_last_inspection %></td>
        <td><%= elevator.certificate_of_inspection %></td>
        <td><%= elevator.information %></td>
        <td><%= elevator.notes %></td>
        <td><%= link_to 'Show', elevator %></td>
        <td><%= link_to 'Edit', edit_elevator_path(elevator) %></td>
        <td><%= link_to 'Destroy', elevator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elevator', new_elevator_path %>

app/views/elevators/new.html.erb
<h1>New Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Back', elevators_path %>

app/views/elevators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Column:</strong>
  <%= @elevator.column %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @elevator.serial_number %>
</p>

<p>
  <strong>Model:</strong>
  <%= @elevator.model %>
</p>

<p>
  <strong>Type:</strong>
  <%= @elevator.type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @elevator.status %>
</p>

<p>
  <strong>Date of commissioning:</strong>
  <%= @elevator.Date_of_commissioning %>
</p>

<p>
  <strong>Date of last inspection:</strong>
  <%= @elevator.date_of_last_inspection %>
</p>

<p>
  <strong>Certificate of inspection:</strong>
  <%= @elevator.certificate_of_inspection %>
</p>

<p>
  <strong>Information:</strong>
  <%= @elevator.information %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @elevator.notes %>
</p>

<%= link_to 'Edit', edit_elevator_path(@elevator) %> |
<%= link_to 'Back', elevators_path %>