config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get '/residential', to: 'home#residential'
  get '/commercial', to: 'home#commercial'
  get '/quote', to: 'home#quote'
  get '/index', to: 'home#index'
  get '/intervention', to: 'home#intervention' 
  post '/create_quotes' =>'quotes#create'
  post '/create_leads' => 'leads#create'
  get '/users/:id' , to: 'users#show'
  get '/users/:id/edit', to: 'users#edit', :as => :user
  patch '/users/:id/edit' => 'users#update'
  get '/update_building/:customer_id', to: 'interventions#updateBuildings'
  get '/update_battery/:building_id', to: 'interventions#updateBattery'
  get '/update_column/:battery_id', to: 'interventions#updateColumn'
  get '/update_elevator/:column_id', to: 'interventions#updateElevator'
  post '/intervention/create_intervention', to: 'interventions#submit'
  resource :intervention

  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'
  # get '/audio', to: 'admin/dashboard#file'

  get 'admin/ibm_call' => 'admin/dashboard#ibm_call'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :customers, dependent: :destroy
    has_many :buildings, dependent: :destroy

  def to_s 
    "Address #" + self.id.to_s
  end
end

app/models/battery.rb
class Battery < ApplicationRecord
  belongs_to :building
  belongs_to :employee
  has_many :columns, dependent: :destroy
  has_many :intervention


  def to_s
    "Battery #" + self.id.to_s
  end
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :customer
  belongs_to :address
  has_one :building_detail, dependent: :destroy
  has_many :batteries, dependent: :destroy
  has_many :intervention
  
  def to_s 
    "Building #" + self.id.to_s
  end

end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
  belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :battery
  has_many :elevators, dependent: :destroy
  has_many :intervention

  def to_s 
    "Column #" + self.id.to_s
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # attr_reader :user_id, :customer_creation_date, :company_name, :company_headquarters_address, :full_name_of_the_company_contact,
  #   :company_contact_phone, :email_of_the_company_contact, :company_description, :technical_authority_phone_for_service, :technical_manager_email_for_service

  belongs_to :user
  belongs_to :address
  has_many :buildings, dependent: :destroy
  has_many :intervention

  def to_s 
    "Customer #" + self.id.to_s
  end
end

app/models/dim_customer.rb
class DimCustomer < ApplicationRecord

end

app/models/elevator.rb
class Elevator < ApplicationRecord
  belongs_to :column
  has_many :intervention

  def to_s
    "Elevator #" + self.id.to_s
  end
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
    belongs_to :user 
    has_many :batteries, dependent: :destroy
    has_many :intervention

        def to_s
        "Employee #" + self.id.to_s
    end
end

app/models/fact_contact.rb
class FactContact < ActiveRecord::Base
    establish_connection(:data_warehouse)
end

app/models/fact_elevator.rb
class FactElevator < ActiveRecord::Base
end

app/models/fact_quote.rb
class FactQuote < ActiveRecord::Base
#      ActiveRecord::Base.establish_connection(:data_warehouse)
    establish_connection(:data_warehouse)
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :employee
    belongs_to :customer
    belongs_to :building
    belongs_to :battery
    belongs_to :column 
    belongs_to :elevator
  
    def to_s
      "Intervention #" + self.id.to_s
    end
    def new
      @intervention = intervention.new
    end 
  end

app/models/lead.rb
class Lead < ApplicationRecord
    has_one_attached :contact_attachment_file
    # after_create :send_email
    # after_create :upload_dropbox
    
    def attachment_path

    end

    def to_s
        "Lead #" + self.id.to_s
    end
    
    private

    def send_email
        Sendgrid.new(self).call
    end

    def upload_dropbox
        Dropbox.new(self).call
    end
end

app/models/quote.rb
# frozen_string_literal: true

class Quote < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :employees, dependent: :destroy
  has_one :customer, dependent: :destroy
  # class_name: "employee", foreign_key: "employees_id" i did remove this one it works with it though

  def to_s
    self.first_name + " " + self.last_name
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < InheritedResources::Base

  private

    def building_params
      params.require(:building).permit(:customer_id, :address_of_the_building, :full_name_of_the_building_administrator, :email_of_the_administrator_of_the_building, :phone_number_of_the_building_administrator, :full_name_of_the_technical_contact_for_the_building, :technical_contact_email_for_the_building, :technical_contact_phone_for_the_building, :address_id)
    end

end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
# frozen_string_literal: true

module QuotesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :address_of_the_building %>
    <%= form.text_field :address_of_the_building %>
  </div>

  <div class="field">
    <%= form.label :full_name_of_the_building_administrator %>
    <%= form.text_field :full_name_of_the_building_administrator %>
  </div>

  <div class="field">
    <%= form.label :email_of_the_administrator_of_the_building %>
    <%= form.text_field :email_of_the_administrator_of_the_building %>
  </div>

  <div class="field">
    <%= form.label :phone_number_of_ %>
    <%= form.text_field :phone_number_of_ %>
  </div>

  <div class="field">
    <%= form.label :the_building_administrator %>
    <%= form.text_field :the_building_administrator %>
  </div>

  <div class="field">
    <%= form.label :full_name_of_the_technical_contact_for_the_building %>
    <%= form.text_field :full_name_of_the_technical_contact_for_the_building %>
  </div>

  <div class="field">
    <%= form.label :technical_contact_email_for %>
    <%= form.text_field :technical_contact_email_for %>
  </div>

  <div class="field">
    <%= form.label :the_building %>
    <%= form.text_field :the_building %>
  </div>

  <div class="field">
    <%= form.label :technical_contact_phone_for_the_building %>
    <%= form.text_field :technical_contact_phone_for_the_building %>
  </div>

  <div class="field">
    <%= form.label :database %>
    <%= form.text_field :database %>
  </div>

  <div class="field">
    <%= form.label :development %>
    <%= form.text_field :development %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Address of the building</th>
      <th>Full name of the building administrator</th>
      <th>Email of the administrator of the building</th>
      <th>Phone number of </th>
      <th>The building administrator</th>
      <th>Full name of the technical contact for the building</th>
      <th>Technical contact email for</th>
      <th>The building</th>
      <th>Technical contact phone for the building</th>
      <th>Database</th>
      <th>Development</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.customer %></td>
        <td><%= building.address_of_the_building %></td>
        <td><%= building.full_name_of_the_building_administrator %></td>
        <td><%= building.email_of_the_administrator_of_the_building %></td>
        <td><%= building.phone_number_of_ %></td>
        <td><%= building.the_building_administrator %></td>
        <td><%= building.full_name_of_the_technical_contact_for_the_building %></td>
        <td><%= building.technical_contact_email_for %></td>
        <td><%= building.the_building %></td>
        <td><%= building.technical_contact_phone_for_the_building %></td>
        <td><%= building.database %></td>
        <td><%= building.development %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @building.customer %>
</p>

<p>
  <strong>Address of the building:</strong>
  <%= @building.address_of_the_building %>
</p>

<p>
  <strong>Full name of the building administrator:</strong>
  <%= @building.full_name_of_the_building_administrator %>
</p>

<p>
  <strong>Email of the administrator of the building:</strong>
  <%= @building.email_of_the_administrator_of_the_building %>
</p>

<p>
  <strong>Phone number of :</strong>
  <%= @building.phone_number_of_ %>
</p>

<p>
  <strong>The building administrator:</strong>
  <%= @building.the_building_administrator %>
</p>

<p>
  <strong>Full name of the technical contact for the building:</strong>
  <%= @building.full_name_of_the_technical_contact_for_the_building %>
</p>

<p>
  <strong>Technical contact email for:</strong>
  <%= @building.technical_contact_email_for %>
</p>

<p>
  <strong>The building:</strong>
  <%= @building.the_building %>
</p>

<p>
  <strong>Technical contact phone for the building:</strong>
  <%= @building.technical_contact_phone_for_the_building %>
</p>

<p>
  <strong>Database:</strong>
  <%= @building.database %>
</p>

<p>
  <strong>Development:</strong>
  <%= @building.development %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>